version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo_medical
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medical_db
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - medical_network
  app:
    build: .
    container_name: migration_app
    depends_on:
      - mongo
    env_file :
      - .env
    command: python migrate_csv_to_mongo.py
    networks:
      - medical_network
volumes:
  mongo_data:
networks:
  medical_network:
    driver: bridge
